version: '3.7'

services:
    app:
        container_name: app
        build:
          context: ./
        ports:
            - "4000:4000"
            - "4020:4020"
        volumes:
            - ./:/var/app
