[check_look]
map_utility_start = 92  # same as MAP_UTILITY_START from _maps.fos                                  # default: 92

[check_look.npc]
fast = true             # skip all vision/hearing/walls logic, just use distance and perception     # default: true 
fast_from = 2200        # starting ProtoId of mobs, from which fast vision check should kick in     # default: 2200
# fast_to = 65535       # maximum ProtoId for mobs                                                  # default: u16::max_value()
